feat: Finalizando o cadastro de itens
DCFS16/dripstore-backend pull request #1
Opened 2023-10-17 21:04 UTC by edilsonnsn

Formulário de cadastro de itens finalizado.

2023-10-19 09:22 UTC, carlosxjm requested changes
Favor, verificar as observações!

2023-10-19 09:22 UTC, carlosxjm commented on views/products/list.ejs
> -  <% } %>
As mudanças nesse arquivo foram irrelevantes, o ideal é que sejam evitadas para deixar o PR mais claro.
Se possível, reverta essas mudanças.

2023-10-19 09:22 UTC, carlosxjm commented on .env.example
> -DATABASE_PORT="3308"
Esse arquivo não deve ser deletado.

2023-10-19 09:22 UTC, carlosxjm commented on public/javascripts/submitProduct.js
> +    price: productPrice.value,
Para montar o objeto que vai ser enviado você pode usar o seguinte código:

```
event.preventDefault();
const formData = new FormData(e.target);
const data = Object.fromEntries(formData);
```

Onde data seria já o objeto com os dados a serem enviados.
Importante perceber que para que isso aconteça os inputs do form deve ter o atributo "name".
Exemplo:
```
<input name="name" type="text" />
<input name="price" type="text" />
```

2023-10-21 12:38 UTC, edilsonnsn commented on public/javascripts/submitProduct.js
> +    price: productPrice.value,
Corrigido!

2023-10-21 12:54 UTC, edilsonnsn commented on views/products/list.ejs
> -  <% } %>
Corrigido

2023-10-21 14:55 UTC, carlosdigital16 requested changes

2023-10-21 14:55 UTC, carlosdigital16 commented on controllers/admin/product.controllers.js
> +    console.log(lastpage)
Por favor, remover console.log

2023-10-21 14:55 UTC, carlosdigital16 commented on controllers/admin/product.controllers.js
> +  let lastpage = 1
Eu acredito que `totalPages`  seria um nome mais padrão isso.
Tudo bem continuar com lastpage mas teria que corrigir o "case": last`P`age

2023-10-21 15:00 UTC, FDiegoRocha approved these changes

2023-10-21 15:00 UTC, carlosdigital16 approved these changes, later dismissed

2023-10-21 15:03 UTC, carlosdigital16 approved these changes
![2IC](https://github.com/DCFS16/dripstore-backend/assets/126329008/60540515-d85a-40d5-ad21-bd8db9c5ebb5)

2023-10-21 15:08 UTC, merged