feat: add delete
DCFS16/dripstore-backend pull request #3
Opened 2023-10-21 13:02 UTC by jessianne

Foi feito a parte de deletar um produto. Se não tiver nada cadastrado, cadastre o primeiro produto. Foi colocado o botão deletar ao lado do produto.

2023-10-21 14:20 UTC, carlosdigital16 requested changes

2023-10-21 14:20 UTC, carlosdigital16 commented on javascripts/deleteProduct.js
Favor, remover o arquivo vazio

2023-10-21 14:20 UTC, carlosdigital16 commented on public/javascripts/deleteProduct.js
> +      .catch(err => console.error(err));
Favor, exibir algum feedback para o usuário caso aconteça algum erro na requisição

2023-10-28 13:09 UTC, carlosdigital16 approved these changes
![image](https://github.com/DCFS16/dripstore-backend/assets/126329008/a217b04e-fc0d-45f1-a8b3-739ca6c6dd6f)

2023-10-28 13:11 UTC, FDiegoRocha approved these changes

2023-10-28 13:13 UTC, merged