Category
DCFS16/dripstore-backend pull request #8
Opened 2023-11-04 15:46 UTC by fabiolapinheiro22

2023-11-18 11:32 UTC, carlosdigital16 requested changes

2023-11-18 11:32 UTC, carlosdigital16 commented on controllers/admin/category.controllers.js
> +    console.log(lastpage)
Remover console.log

2023-11-18 11:32 UTC, carlosdigital16 commented on controllers/api/categories.controllers.js
> +  console.log(category)
Remover console

2023-11-18 11:32 UTC, carlosdigital16 commented on controllers/api/categories.controllers.js
> +    // products,
Remover comentário

2023-11-18 14:27 UTC, FDiegoRocha approved these changes

2023-12-09 12:35 UTC, carlosdigital16 approved these changes
Great job! 🥇

2023-12-09 12:36 UTC, merged